float64 left_x
float64 left_y
float64 left_z
float64 left_rx
float64 left_ry
float64 left_rz

float64 right_x
float64 right_y
float64 right_z
float64 right_rx
float64 right_ry
float64 right_rz
---
bool success
string message
